// Textes de l'interface publique, en kréyòl (kr) et en français (fr).
// Les deux langues ont exactement les mêmes clés. Les {accolades} sont remplacées
// par des valeurs (nombre de résultats, mot cherché…) : ne pas les traduire.

export const LANGUES = ['kr', 'fr'];
export const LANGUE_DEFAUT = 'kr';

export const TEXTES = {
  kr: {
    htmlLang: 'gcf',
    site: {
      nom: 'Mofwazé',
      sousTitre: 'Kréyòl Gwadloupéyen ↔ Fransé',
      description:
        'Diksyonnè kréyòl gwadloupéyen ↔ fransé : chèché on mo, touvé mofwazaj a-y, sinonim é ègzanp. Épi chak jou, on mo nouvo pou dékouvè.',
    },
    nav: {
      accueil: 'Kaz',
      dictionnaire: 'Diksyonnè',
      jeu: 'Mo kaché',
      proposer: 'Pwopozé on mo',
      aPropos: 'Sou sit-la',
      menu: 'Menu',
      fermer: 'Fèmé',
    },
    langue: {
      titre: 'Lang',
      kr: 'Kréyòl',
      fr: 'Fransé',
    },
    recherche: {
      krFr: 'Kréyòl → Fransé',
      frKr: 'Fransé → Kréyòl',
      inverser: 'Chanjé sans',
      placeholderKr: 'Maké on mo kréyòl…',
      placeholderFr: 'Maké on mo fransé…',
      bouton: 'Chèché',
      effacer: 'Éfasé',
      titre: 'Chèché',
      resultats: '{n} rézilta pou « {q} »',
      resultat: '1 rézilta pou « {q} »',
      aucun: 'Pon mo touvé pou « {q} ».',
      essayerAutreSens: 'Éséyé chèché « {q} » an fransé',
      essayerAutreSensKr: 'Éséyé chèché « {q} » an kréyòl',
      vide: 'Maké on mo pou chèché adan diksyonnè-la.',
      dansTraductions: 'Yo ka touvé « {q} » osi adan sé mofwazaj-lasa',
      termeFrancais: 'Mo fransé',
      voirTout: 'Vwè tout',
    },
    accueil: {
      titre: 'Chèché on mo, touvé sans a-y',
      stats: '{mots} mo kréyòl · {sens} sans · {termes} mo fransé',
      motDuJour: 'Mo a jou-la',
      voirFiche: 'Vwè tout fich-la',
      jeuTitre: 'Mo kaché',
      jeuTexte: 'Touvé mo kréyòl a 5 lèt-la an 6 kou. On mo nouvo chak jou !',
      jeuBouton: 'Jwé',
      jeuNumero: 'Jé n°{n}',
      parcourir: 'Gadé diksyonnè-la lèt pa lèt',
      contribuerTitre: 'Ou vwè on érè ? On mo manké ?',
      contribuerTexte:
        'Diksyonnè-la ka grandi èvè zòt. Pwopozé on korèksyon oben on mo nouvo : nou ka li chak popozisyon anvan i antré.',
      contribuerBouton: 'Pwopozé on mo',
    },
    fiche: {
      traductions: 'Mofwazaj',
      variantes: 'Ou pé maké-y osi',
      synonymes: 'Sinonim',
      termesFr: 'An fransé',
      locutions: 'Èsprésyon é ègzanp',
      voirAussi: 'Vwè osi',
      proposer: 'Pwopozé on korèksyon',
      proposerTexte: 'On érè, on sans ki manké, on ègzanp ?',
      partager: 'Patajé',
      lienCopie: 'Lyen-la kopyé !',
      precedent: 'Mo avan',
      suivant: 'Mo apré',
      pasDeTraduction: 'Pòkò ni mofwazaj pou mo-lasa.',
      metaTitre: '{mot} : mofwazaj an fransé',
      metaDescription: '{mot} an kréyòl gwadloupéyen : {sens}',
    },
    francais: {
      titre: '« {terme} » an kréyòl',
      intro: 'Mo kréyòl ki ka di « {terme} » :',
      metaDescription: 'Kijan yo ka di « {terme} » an kréyòl gwadloupéyen : {mots}',
    },
    lettre: {
      titre: 'Diksyonnè – lèt {l}',
      compte: '{n} mo ka koumansé pa {l}',
      metaDescription: 'Tout sé mo kréyòl gwadloupéyen ki ka koumansé pa {l}, èvè mofwazaj a yo an fransé.',
    },
    pagination: {
      precedent: 'Avan',
      suivant: 'Apré',
      page: 'Paj {n} / {total}',
    },
    jeu: {
      titre: 'Mo kaché',
      sousTitre: 'Touvé mo kréyòl a jou-la an 6 kou',
      numero: 'n°{n}',
      regles: 'Kijan pou jwé',
      regle1: 'Maké on mo kréyòl a 5 lèt, apré apiyé si « Antré ».',
      regleBon: 'Lèt-la bon é i an bon plas a-y.',
      reglePlace: 'Lèt-la adan mo-la, men pa an plas-lasa.',
      regleAbsent: 'Lèt-la pa adan mo-la.',
      regleAccents: 'Aksan pa ka konté : É = E, È = E, Ò = O.',
      regleDico: 'Sé mo a diksyonnè-la sèlman ki bon.',
      entree: 'Antré',
      effacer: 'Éfasé',
      tropCourt: 'Mo-la pa ni 5 lèt',
      inconnu: 'Mo-lasa pa adan diksyonnè-la',
      erreur: 'On problèm rivé, éséyé ankò',
      gagne: ['Fòs a-w !', 'Bravo !', 'Bèl travay !', 'Ou touvé-y !', 'Woulo !', 'Pa pi mal !'],
      perdu: 'Domaj ! Mo-la té :',
      voirFiche: 'Vwè fich a mo-la',
      prochain: 'Prochen mo kaché adan',
      partager: 'Patajé rézilta a-w',
      copie: 'Rézilta kopyé !',
      stats: 'Statistik',
      joues: 'Jé',
      victoires: '% gangné',
      serie: 'Séri',
      meilleureSerie: 'Pli bèl séri',
      distribution: 'Konmen kou',
      fermer: 'Fèmé',
    },
    proposer: {
      titre: 'Pwopozé on mo oben on korèksyon',
      intro: 'Diksyonnè-la ka grandi èvè zòt. Chak popozisyon ka li anvan i antré adan diksyonnè-la.',
      type: 'Sa ou vlé fè ?',
      typeAjout: 'Ajouté on mo',
      typeCorrection: 'Korijé on mo',
      typeRemarque: 'Ot bagay',
      corrige: 'Ou ka korijé fich-la : {mot}',
      choisirMot: 'Ki mo ou vlé korijé ?',
      choisirMotAide: 'Chèché mo-la, apré apiyé si-y.',
      changerMot: 'Chwazi on lòt mo',
      mot: 'Mo kréyòl',
      variantes: 'Ot fason maké-y',
      variantesAide: 'Si i ni, séparé yo èvè « , »',
      sens: 'Sans {n}',
      traduction: 'Mofwazaj an fransé',
      synonymes: 'Sinonim',
      synonymesAide: 'Séparé yo èvè « , »',
      ajouterSens: 'Ajouté on sans',
      retirer: 'Tiré',
      monter: 'Monté',
      descendre: 'Désann',
      locution: 'Èsprésyon oben ègzanp',
      expression: 'Èsprésyon an kréyòl',
      locutionTraduction: 'Sa i vlé di an fransé',
      exempleKr: 'Ègzanp an kréyòl',
      exempleFr: 'Ègzanp-la an fransé',
      ajouterLocution: 'Ajouté on èsprésyon oben on ègzanp',
      message: 'Mésaj',
      messageAide: 'Ki sa ki pa bon ? Kimoun ka di-y konsa ? Tout sa ki pé rédé nou.',
      nom: 'Non a-w',
      email: 'Adrès mèl a-w',
      facultatif: 'si ou vlé',
      notifier: 'Vèti-mwen lè popozisyon an mwen antré adan diksyonnè-la',
      envoyer: 'Voyé',
      envoi: 'Nou ka voyé…',
      merciTitre: 'Mèsi onlo !',
      merciTexte: 'Nou byen resevwa popozisyon a-w. Nou ké li-y talè.',
      encore: 'Pwopozé on dòt mo',
      erreurMot: 'Maké mo kréyòl-la.',
      erreurTraduction: 'Maké omwen on mofwazaj.',
      erreurMessage: 'Maké on ti mésaj.',
      erreurRienChange: 'Ou pa chanjé ayen : chanjé fich-la oben maké on mésaj.',
      erreurEmail: 'Adrès mèl-la pa bon.',
      erreurTrop: 'Ou voyé twòp popozisyon. Éséyé ankò pli ta.',
      erreurTechnique: 'On problèm rivé. Éséyé ankò pli ta.',
      contact: 'Ou pé osi ékri nou dirèkman :',
      rgpd:
        'Non é adrès mèl a-w pa obligatwa : nou ka sèvi-yo sèlman pou trété popozisyon a-w, nou pa ka pibliyé-yo. Lè ou ka voyé, ou dakò popozisyon a-w antré adan diksyonnè-la, menm si nou ka ranjé-y.',
      enSavoirPlus: 'An savé plis',
    },
    aPropos: {
      titre: 'Sou sit-la',
      p1: 'Mofwazé sé on diksyonnè kréyòl gwadloupéyen ↔ fransé, gratis é pou toutmoun.',
      p2: 'Ou pé chèché on mo kréyòl pou touvé mofwazaj a-y an fransé, oben chèché on mo fransé pou vwè kijan yo ka di-y an kréyòl.',
      p3: 'Chak jou, ni on mo a jou-la pou aprann, é on mo kaché pou touvé.',
      contribuerTitre: 'Rédé diksyonnè-la',
      contribuer: 'Diksyonnè-la pa fini. Si ou vwè on érè oben si on mo manké, pwopozé-y : nou ka li chak popozisyon anvan i antré.',
      livreTitre: 'Pou alé pli lwen',
      livre: 'Si ou vlé ranjé kréyòl a-w, ou pé li « Dictionnaire Créole Guadeloupéen/Français », Éditions Orphie, 2013.',
      contactTitre: 'Ékri nou',
    },
    pied: {
      livre: 'Pou alé pli lwen : « Dictionnaire Créole Guadeloupéen/Français », Éditions Orphie, 2013.',
      contact: 'Ékri nou',
      liens: 'Lyen',
      mentions: 'Mentions légales',
      confidentialite: 'Konfidansyalité',
    },
    legal: {
      noteFrancais: 'Paj-lasa ka égzisté an fransé sèlman.',
    },
    erreurs: {
      introuvableTitre: 'Paj-lasa pa ka égzisté',
      introuvableTexte: 'Nou pa touvé sa ou ka chèché.',
      retourAccueil: 'Rètounen an kaz',
      techniqueTitre: 'On problèm rivé',
      techniqueTexte: 'Sit-la pa pé réponn atò. Éséyé ankò talè.',
      reessayer: 'Éséyé ankò',
    },
  },

  fr: {
    htmlLang: 'fr',
    site: {
      nom: 'Mofwazé',
      sousTitre: 'Créole guadeloupéen ↔ Français',
      description:
        'Dictionnaire créole guadeloupéen ↔ français : cherchez un mot, trouvez sa traduction, ses synonymes et des exemples. Et chaque jour, un nouveau mot à découvrir.',
    },
    nav: {
      accueil: 'Accueil',
      dictionnaire: 'Dictionnaire',
      jeu: 'Mo kaché',
      proposer: 'Proposer un mot',
      aPropos: 'À propos',
      menu: 'Menu',
      fermer: 'Fermer',
    },
    langue: {
      titre: 'Langue',
      kr: 'Créole',
      fr: 'Français',
    },
    recherche: {
      krFr: 'Créole → Français',
      frKr: 'Français → Créole',
      inverser: 'Inverser',
      placeholderKr: 'Tapez un mot créole…',
      placeholderFr: 'Tapez un mot français…',
      bouton: 'Chercher',
      effacer: 'Effacer',
      titre: 'Recherche',
      resultats: '{n} résultats pour « {q} »',
      resultat: '1 résultat pour « {q} »',
      aucun: 'Aucun mot trouvé pour « {q} ».',
      essayerAutreSens: 'Chercher « {q} » en français',
      essayerAutreSensKr: 'Chercher « {q} » en créole',
      vide: 'Tapez un mot pour chercher dans le dictionnaire.',
      dansTraductions: '« {q} » apparaît aussi dans ces traductions',
      termeFrancais: 'Mot français',
      voirTout: 'Tout voir',
    },
    accueil: {
      titre: 'Cherchez un mot, trouvez son sens',
      stats: '{mots} mots créoles · {sens} sens · {termes} mots français',
      motDuJour: 'Le mot du jour',
      voirFiche: 'Voir la fiche complète',
      jeuTitre: 'Mo kaché',
      jeuTexte: 'Devinez le mot créole de 5 lettres en 6 essais. Un nouveau mot chaque jour !',
      jeuBouton: 'Jouer',
      jeuNumero: 'Partie n°{n}',
      parcourir: 'Parcourir le dictionnaire lettre par lettre',
      contribuerTitre: 'Une erreur ? Un mot manquant ?',
      contribuerTexte:
        'Le dictionnaire s’enrichit grâce à vous. Proposez une correction ou un nouveau mot : chaque proposition est relue avant d’être ajoutée.',
      contribuerBouton: 'Proposer un mot',
    },
    fiche: {
      traductions: 'Traductions',
      variantes: 'Autres graphies',
      synonymes: 'Synonymes',
      termesFr: 'En français',
      locutions: 'Expressions et exemples',
      voirAussi: 'Voir aussi',
      proposer: 'Proposer une correction',
      proposerTexte: 'Une erreur, un sens manquant, un exemple ?',
      partager: 'Partager',
      lienCopie: 'Lien copié !',
      precedent: 'Mot précédent',
      suivant: 'Mot suivant',
      pasDeTraduction: 'Pas encore de traduction pour ce mot.',
      metaTitre: '{mot} : traduction en français',
      metaDescription: '{mot} en créole guadeloupéen : {sens}',
    },
    francais: {
      titre: '« {terme} » en créole',
      intro: 'Mots créoles qui traduisent « {terme} » :',
      metaDescription: 'Comment dire « {terme} » en créole guadeloupéen : {mots}',
    },
    lettre: {
      titre: 'Dictionnaire – lettre {l}',
      compte: '{n} mots commencent par {l}',
      metaDescription: 'Tous les mots créoles guadeloupéens commençant par {l}, avec leur traduction en français.',
    },
    pagination: {
      precedent: 'Précédent',
      suivant: 'Suivant',
      page: 'Page {n} / {total}',
    },
    jeu: {
      titre: 'Mo kaché',
      sousTitre: 'Trouvez le mot créole du jour en 6 essais',
      numero: 'n°{n}',
      regles: 'Comment jouer',
      regle1: 'Tapez un mot créole de 5 lettres, puis appuyez sur « Entrée ».',
      regleBon: 'La lettre est bonne et bien placée.',
      reglePlace: 'La lettre est dans le mot, mais pas à cette place.',
      regleAbsent: 'La lettre n’est pas dans le mot.',
      regleAccents: 'Les accents ne comptent pas : É = E, È = E, Ò = O.',
      regleDico: 'Seuls les mots du dictionnaire sont acceptés.',
      entree: 'Entrée',
      effacer: 'Effacer',
      tropCourt: 'Il faut 5 lettres',
      inconnu: 'Ce mot n’est pas dans le dictionnaire',
      erreur: 'Une erreur est survenue, réessayez',
      gagne: ['Génial !', 'Bravo !', 'Très bien !', 'Trouvé !', 'Bien joué !', 'Ouf !'],
      perdu: 'Dommage ! Le mot était :',
      voirFiche: 'Voir la fiche du mot',
      prochain: 'Prochain mot kaché dans',
      partager: 'Partager mon résultat',
      copie: 'Résultat copié !',
      stats: 'Statistiques',
      joues: 'Parties',
      victoires: '% victoires',
      serie: 'Série',
      meilleureSerie: 'Meilleure série',
      distribution: 'Nombre d’essais',
      fermer: 'Fermer',
    },
    proposer: {
      titre: 'Proposer un mot ou une correction',
      intro: 'Le dictionnaire s’enrichit grâce à vous. Chaque proposition est relue avant d’être ajoutée.',
      type: 'Que voulez-vous faire ?',
      typeAjout: 'Ajouter un mot',
      typeCorrection: 'Corriger un mot',
      typeRemarque: 'Autre remarque',
      corrige: 'Vous corrigez la fiche : {mot}',
      choisirMot: 'Quel mot voulez-vous corriger ?',
      choisirMotAide: 'Cherchez le mot, puis cliquez dessus.',
      changerMot: 'Choisir un autre mot',
      mot: 'Mot créole',
      variantes: 'Autres graphies',
      variantesAide: 'S’il y en a, séparées par des virgules',
      sens: 'Sens {n}',
      traduction: 'Traduction en français',
      synonymes: 'Synonymes',
      synonymesAide: 'Séparés par des virgules',
      ajouterSens: 'Ajouter un sens',
      retirer: 'Retirer',
      monter: 'Monter',
      descendre: 'Descendre',
      locution: 'Expression ou exemple',
      expression: 'Expression en créole',
      locutionTraduction: 'Sens en français',
      exempleKr: 'Exemple en créole',
      exempleFr: 'Exemple traduit en français',
      ajouterLocution: 'Ajouter une expression ou un exemple',
      message: 'Message',
      messageAide: 'Qu’est-ce qui ne va pas ? D’où vient cet usage ? Toute précision nous aide.',
      nom: 'Votre nom',
      email: 'Votre e-mail',
      facultatif: 'facultatif',
      notifier: 'Me prévenir quand ma proposition est ajoutée au dictionnaire',
      envoyer: 'Envoyer',
      envoi: 'Envoi…',
      merciTitre: 'Merci beaucoup !',
      merciTexte: 'Votre proposition a bien été reçue. Nous la relirons prochainement.',
      encore: 'Faire une autre proposition',
      erreurMot: 'Indiquez le mot créole.',
      erreurTraduction: 'Indiquez au moins une traduction.',
      erreurMessage: 'Écrivez un petit message.',
      erreurRienChange: 'Rien n’a changé : modifiez la fiche ou écrivez un message.',
      erreurEmail: 'Cette adresse e-mail n’est pas valide.',
      erreurTrop: 'Trop de propositions envoyées. Réessayez plus tard.',
      erreurTechnique: 'Une erreur est survenue. Réessayez plus tard.',
      contact: 'Vous pouvez aussi nous écrire directement :',
      rgpd:
        'Votre nom et votre e-mail sont facultatifs : ils servent uniquement à traiter votre proposition et ne sont jamais publiés. En envoyant, vous acceptez que votre proposition soit ajoutée au dictionnaire, éventuellement modifiée.',
      enSavoirPlus: 'En savoir plus',
    },
    aPropos: {
      titre: 'À propos',
      p1: 'Mofwazé est un dictionnaire créole guadeloupéen ↔ français, gratuit et ouvert à tous.',
      p2: 'Cherchez un mot créole pour trouver sa traduction en français, ou un mot français pour découvrir comment on le dit en créole.',
      p3: 'Chaque jour, un mot du jour à apprendre et un mot kaché à deviner.',
      contribuerTitre: 'Contribuer',
      contribuer: 'Le dictionnaire n’est jamais fini. Si vous repérez une erreur ou un mot manquant, proposez-le : chaque proposition est relue avant d’être ajoutée.',
      livreTitre: 'Pour aller plus loin',
      livre: 'Pour approfondir votre créole : « Dictionnaire Créole Guadeloupéen/Français », Éditions Orphie, 2013.',
      contactTitre: 'Nous écrire',
    },
    pied: {
      livre: 'Pour aller plus loin : « Dictionnaire Créole Guadeloupéen/Français », Éditions Orphie, 2013.',
      contact: 'Contact',
      liens: 'Liens',
      mentions: 'Mentions légales',
      confidentialite: 'Confidentialité',
    },
    legal: {
      noteFrancais: '',
    },
    erreurs: {
      introuvableTitre: 'Cette page n’existe pas',
      introuvableTexte: 'Nous n’avons pas trouvé ce que vous cherchez.',
      retourAccueil: 'Retour à l’accueil',
      techniqueTitre: 'Une erreur est survenue',
      techniqueTexte: 'Le site ne répond pas pour le moment. Réessayez dans un instant.',
      reessayer: 'Réessayer',
    },
  },
};

// Remplace les {clés} d'un texte : f('{n} mots', { n: 3 })
export function f(texte, valeurs = {}) {
  return String(texte).replace(/\{(\w+)\}/g, (_, cle) => (valeurs[cle] ?? `{${cle}}`).toString());
}

export function formaterNombre(n) {
  return new Intl.NumberFormat('fr-FR').format(n);
}
